import packages

In [ ]:
#imports
import warnings
warnings.filterwarnings('ignore')
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# mounting drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Read File

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/crime1.csv')

In [ ]:
data.head()

crime_id  report_num                        address             offense_de  \
0   3021501  1702050013      W Chicago St & Carlin Ave                  ARSON   
1   3046060  1704040001       Cass Ave & W Canfield St                  ARSON   
2   3049686  1704110374          Margareta St & Oak Dr               TRESPASS   
3   3056001  1704270155         Peters St & S Ethel St  FRAUD - IMPERSONATION   
4   3205123  1804300085  S M 39 Service Drive & Joy Rd                ROBBERY   

  offense_ca  state_offe arrest_cha             charge_des incident_t  \
0      ARSON        2099      20000                  ARSON     2/5/17   
1      ARSON        2099      20000                  ARSON     4/4/17   
2      OTHER        5701      57001               TRESPASS    4/12/17   
3      FRAUD        2603      26003  FRAUD - IMPERSONATION    4/23/17   
4    ROBBERY        1201      12000                ROBBERY    4/28/18   

   day_of_wee  ...  scout_car_  precinct         block_id  \
0           7  ...        0207        02  261635351002016   
1           2  ...        0309        03  261635203001000   
2           2  ...        1209        12  261635384001009   
3           7  ...        0415        04  261635248002001   
4           5  ...        0610        06  261635460001000   

                Cities  council_di zip_code  longitude   latitude  ibr_date  \
0     Plymouth-Hubbell           7    48227 -83.178905  42.365775   5/15/17   
1              Midtown           6    48201 -83.064139  42.351578   1/16/18   
2  University District           2    48221 -83.138532  42.428059   5/15/17   
3              Boynton           6    48217 -83.158897  42.259713   5/15/17   
4           Warrendale           7    48228 -83.216912  42.357846    5/1/18   

   oid  
0    1  
1    2  
2    3  
3    4  
4    5  

[5 rows x 22 columns]

In [ ]:
data = data.dropna()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 531979 entries, 0 to 531998
Data columns (total 22 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   crime_id    531979 non-null  int64  
 1   report_num  531979 non-null  int64  
 2   address     531979 non-null  object 
 3   offense_de  531979 non-null  object 
 4   offense_ca  531979 non-null  object 
 5   state_offe  531979 non-null  int64  
 6   arrest_cha  531979 non-null  object 
 7   charge_des  531979 non-null  object 
 8   incident_t  531979 non-null  object 
 9   day_of_wee  531979 non-null  int64  
 10  hour_of_da  531979 non-null  int64  
 11  year        531979 non-null  int64  
 12  scout_car_  531979 non-null  object 
 13  precinct    531979 non-null  object 
 14  block_id    531979 non-null  int64  
 15  Cities      531979 non-null  object 
 16  council_di  531979 non-null  int64  
 17  zip_code    531979 non-null  int64  
 18  longitude   531979 non-null  float64
 19  latitud

In [ ]:
#data['incident_t'] = pd.to_datetime(data['incident_t'], errors='coerce')

In [ ]:
#data['day'] = data['incident_t'].dt.day
#data['month'] = data['incident_t'].dt.month
#data['year'] = data['incident_t'].dt.year

In [ ]:
data['offense_ca'].value_counts()


offense_ca
ASSAULT                   96724
LARCENY                   79206
DAMAGE TO PROPERTY        68860
AGGRAVATED ASSAULT        54941
STOLEN VEHICLE            47357
FRAUD                     42391
BURGLARY                  40910
WEAPONS OFFENSES          19457
ROBBERY                   12605
DANGEROUS DRUGS           10261
STOLEN PROPERTY           10178
SEX OFFENSES               7419
OBSTRUCTING JUDICIARY      7208
OBSTRUCTING THE POLICE     5368
SEXUAL ASSAULT             4834
ARSON                      4381
OUIL                       3386
FAMILY OFFENSE             2837
RUNAWAY                    2568
MISCELLANEOUS              2242
HOMICIDE                   1859
DISORDERLY CONDUCT         1766
OTHER                      1547
FORGERY                    1493
KIDNAPPING                 1227
LIQUOR                      488
EXTORTION                   292
JUSTIFIABLE HOMICIDE        130
SOLICITATION                 34
GAMBLING                     10
Name: count, dtype: int64

In [ ]:
data['offense_ca'].count()

531979

In [ ]:
data = data[['offense_ca','day_of_wee','hour_of_da','Cities','council_di','zip_code']]

In [ ]:
def change_label(df):
    df.offense_ca.replace(['ASSAULT','AGGRAVATED ASSAULT', 'ROBBERY', 'SEXUAL ASSAULT', 'HOMICIDE', 'JUSTIFIABLE HOMICIDE', 'KIDNAPPING', 'ARSON'], 'ViolentCrime', inplace=True)
    df.offense_ca.replace(['LARCENY', 'DAMAGE TO PROPERTY', 'BURGLARY', 'STOLEN VEHICLE', 'STOLEN PROPERTY', 'FRAUD', 'FORGERY'], 'PropertyCrime', inplace=True)
    df.offense_ca.replace(['DANGEROUS DRUGS', 'WEAPONS OFFENSES', 'OBSTRUCTING JUDICIARY', 'OBSTRUCTING THE POLICE', 'DISORDERLY CONDUCT', 'FAMILY OFFENSE', 'RUNAWAY', 'MISCELLANEOUS', 'OTHER'], 'DrugsCrime', inplace=True)
    df.offense_ca.replace(['OUIL','SEX OFFENSES','LIQUOR', 'EXTORTION', 'SOLICITATION', 'GAMBLING'], 'MiscCrime', inplace=True)

In [ ]:
change_label(data)

In [ ]:
data['offense_ca'].value_counts()

offense_ca
PropertyCrime    290395
ViolentCrime     176701
DrugsCrime        53254
MiscCrime         11629
Name: count, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 531979 entries, 0 to 531998
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   offense_ca  531979 non-null  object
 1   day_of_wee  531979 non-null  int64 
 2   hour_of_da  531979 non-null  int64 
 3   Cities      531979 non-null  object
 4   council_di  531979 non-null  int64 
 5   zip_code    531979 non-null  int64 
dtypes: int64(4), object(2)
memory usage: 28.4+ MB


In [ ]:
# Convert column 'A' to string
#data['precinct'] = data['precinct'].astype(str)

In [ ]:

#import pandas as pd
# Create a new DataFrame without the rows where the column has the specified value
#data = data[~data['zip_code'].isin([48236, 48238, 48239, 48243])]
data.count()
#data['offense_ca'].value_counts()

offense_ca    531979
day_of_wee    531979
hour_of_da    531979
Cities        531979
council_di    531979
zip_code      531979
dtype: int64

preprocessing

In [ ]:
data.to_csv('/content/drive/MyDrive/reduced_set.csv', index=False)

In [ ]:
data = data[~((data['zip_code'].isin([48201, 48202, 48203, 48203, 48204, 48205])) & (data['offense_ca'].isin(['DrugsCrime','PropertyCrime'])))]
data = data[~((data['zip_code'].isin([48206, 48207, 48208, 48209, 48210, 48211])) & (data['offense_ca'].isin(['PropertyCrime','ViolentCrime'])))]
data = data[~((data['zip_code'].isin([48212, 48213, 48214, 48215])) & (data['offense_ca'].isin(['DrugsCrime','ViolentCrime'])))]
data = data[~((data['zip_code'].isin([48216, 48217, 48219, 48221,48223])) & (data['offense_ca'].isin(['PropertyCrime'])))]
data = data[~((data['zip_code'].isin([48224, 48226, 48227, 48228])) & (data['offense_ca'].isin(['DrugsCrime','ViolentCrime'])))]
data = data[~((data['zip_code'].isin([48234, 48235])) & (data['offense_ca'].isin(['ViolentCrime','PropertyCrime'])))]
data = data[~((data['zip_code'].isin([48236, 48238, 48239, 48243])) & (data['offense_ca'].isin(['ViolentCrime','PropertyCrime'])))]


In [ ]:
data.count()

offense_ca    190620
day_of_wee    190620
hour_of_da    190620
Cities        190620
council_di    190620
zip_code      190620
dtype: int64

In [ ]:
data['offense_ca'].value_counts()

offense_ca
PropertyCrime    96373
ViolentCrime     59136
DrugsCrime       23482
MiscCrime        11629
Name: count, dtype: int64

In [ ]:
# prompt: suggest a model that gives good accuracy for the data in dataframe
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
label_encoder_off_ca = preprocessing.LabelEncoder()


# Encode labels in column 'species'.
data['offense_ca']= label_encoder_off_ca.fit_transform(data['offense_ca'])
#data['zip_code']= label_encoder.fit_transform(data['zip_code'])
data['day_of_wee']= label_encoder.fit_transform(data['day_of_wee'])
data['hour_of_da']= label_encoder.fit_transform(data['hour_of_da'])
#scout_car_= label_encoder.fit_transform(data['scout_car_'])
#data['precinct']= label_encoder.fit_transform(data['precinct'])
data['Cities'] = label_encoder.fit_transform(data['Cities'])
data['council_di']= label_encoder.fit_transform(data['council_di'])
data['zip_code']= label_encoder.fit_transform(data['zip_code'])



# Separate features and target
X = data.drop('offense_ca', axis=1)
y = data['offense_ca']

# Get the categories associated with each label encoder value for each column
categories_offense_ca = label_encoder_off_ca.classes_


In [ ]:
data.count()

offense_ca    190620
day_of_wee    190620
hour_of_da    190620
Cities        190620
council_di    190620
zip_code      190620
dtype: int64

Split

In [ ]:
print(categories_offense_ca)

['DrugsCrime' 'MiscCrime' 'PropertyCrime' 'ViolentCrime']


In [ ]:
# Split data into training and test sets
from sklearn.model_selection import train_test_split,cross_val_score
# Split data into training, validation, and test sets
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # x_train_full = 80 x_test = 20
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1, random_state=42)  # 0.25 x 0.8 = 0.2
# x_train 72 x_val 8






In [ ]:
X_train.count()



day_of_wee    137246
hour_of_da    137246
Cities        137246
council_di    137246
zip_code      137246
dtype: int64

In [ ]:
X_val.count()

day_of_wee    15250
hour_of_da    15250
Cities        15250
council_di    15250
zip_code      15250
dtype: int64

In [ ]:
X_test.count()

day_of_wee    38124
hour_of_da    38124
Cities        38124
council_di    38124
zip_code      38124
dtype: int64

In [ ]:
# Ensure the data is in the correct format if needed
X_train = X_train.values
X_val = X_val.values
X_test = X_test.values

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix
import seaborn as sns
import numpy as np
# Create KNN classifier with k=3,5,7,9,11
n_neighbors = [3,5,7,9,11]
for i in n_neighbors:
  print(f"KNN with k={i}")
  knn = KNeighborsClassifier(n_neighbors=i)
  # Perform cross-validation with 5 folds
  cv_scores = cross_val_score(knn, X_train, y_train, cv=5)
  # Print the cross-validation scores
  print("Cross-validation scores:", cv_scores)
  print("Mean cross-validation score:", np.mean(cv_scores))
  # Fit the model on the training data
  knn.fit(X_train, y_train)
  # Predict on the validation data
  y_val_pred = knn.predict(X_val)
  val_accuracy = accuracy_score(y_val, y_val_pred)
  print("Validation Accuracy:", val_accuracy)
  # Predict the labels for test set
  y_pred = knn.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print("Test Data Accuracy:", accuracy)
  test_class_report = classification_report(y_test, y_pred)
  test_conf_matrix = confusion_matrix(y_test, y_pred)

  print(f"Test Accuracy: {accuracy:.2f}")
  print("Test Classification Report:")
  print(test_class_report)
  print("Test Confusion Matrix:")
  print(test_conf_matrix)

KNN with k=3
Cross-validation scores: [0.8820765  0.87944916 0.88189005 0.88305585 0.88156217]
Mean cross-validation score: 0.8816067465007634
Validation Accuracy: 0.8864262295081967
Test Data Accuracy: 0.8797870108068409
Test Accuracy: 0.88
Test Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.67      0.69      4741
           1       0.42      0.24      0.30      2369
           2       0.97      0.99      0.98     19169
           3       0.85      0.92      0.89     11845

    accuracy                           0.88     38124
   macro avg       0.74      0.70      0.71     38124
weighted avg       0.87      0.88      0.87     38124

Test Confusion Matrix:
[[ 3161   284     8  1288]
 [  562   560   665   582]
 [    2   234 18933     0]
 [  710   245     3 10887]]
KNN with k=5
Cross-validation scores: [0.88998179 0.89030566 0.89241867 0.89340231 0.89096142]
Mean cross-validation score: 0.8914139678546755
Validation Accuracy:

In [ ]:
#Logistic regression model implementation
# Train different models and evaluate their accuracy
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import numpy as np

degree = [2,3,7]
for i in degree:
    lg_model = make_pipeline(PolynomialFeatures(i), LogisticRegression(C=1.0, solver='saga', max_iter=100))
    # Compute cross-validation scores
    cv_scores = cross_val_score(lg_model, X_train, y_train, cv=5)
    print(f"Model: Logistic regression")
    print(f"Cross-validation scores: {cv_scores}")
    print(f"Mean cross-validation score: {np.mean(cv_scores)}\n")
    # Fit the model on the training data
    lg_model.fit(X_train, y_train)

    # Predict on the validation data
    y_val_pred = lg_model.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    val_class_report = classification_report(y_val, y_val_pred)
    val_conf_matrix = confusion_matrix(y_val, y_val_pred)

    print(f"Model: Logistic Regression")
    print(f"Validation Accuracy: {val_accuracy:.2f}")
    print("Validation Classification Report:")
    print(val_class_report)
    print("Validation Confusion Matrix:")
    print(val_conf_matrix)
    print()

    # Predict on the test data
    y_test_pred = lg_model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_class_report = classification_report(y_test, y_test_pred)
    test_conf_matrix = confusion_matrix(y_test, y_test_pred)

    print(f"Test Accuracy: {test_accuracy:.2f}")
    print("Test Classification Report:")
    print(test_class_report)
    print("Test Confusion Matrix:")
    print(test_conf_matrix)

Model: Logistic regression
Cross-validation scores: [0.72466302 0.72294073 0.72264928 0.72461656 0.722795  ]
Mean cross-validation score: 0.7235329180442006

Model: Logistic Regression
Validation Accuracy: 0.74
Validation Classification Report:
              precision    recall  f1-score   support

           0       0.23      0.02      0.04      1819
           1       0.00      0.00      0.00       928
           2       0.75      0.93      0.83      7789
           3       0.72      0.84      0.78      4714

    accuracy                           0.74     15250
   macro avg       0.43      0.45      0.41     15250
weighted avg       0.63      0.74      0.67     15250

Validation Confusion Matrix:
[[  40    0 1133  646]
 [  17    0  504  407]
 [ 112    0 7230  447]
 [   7    0  767 3940]]

Test Accuracy: 0.73
Test Classification Report:
              precision    recall  f1-score   support

           0       0.20      0.02      0.04      4741
           1       0.00      0.00      0

In [ ]:
# decision tree implementation
from sklearn.tree import DecisionTreeClassifier
depth = [5,10,15,20]
for i in depth:
    dt_model = DecisionTreeClassifier(max_depth=i, min_samples_split=5, min_samples_leaf=2)
    # Compute cross-validation scores
    cv_scores = cross_val_score(dt_model, X_train, y_train, cv=5)
    print(f"Model: Decision Tree")
    print(f"Cross-validation scores: {cv_scores}")
    print(f"Mean cross-validation score: {np.mean(cv_scores)}\n")
    # Fit the model on the training data
    dt_model.fit(X_train, y_train)

    # Predict on the validation data
    y_val_pred = dt_model.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    val_class_report = classification_report(y_val, y_val_pred)
    val_conf_matrix = confusion_matrix(y_val, y_val_pred)

    print(f"Model: Logistic Regression")
    print(f"Validation Accuracy: {val_accuracy:.2f}")
    print("Validation Classification Report:")
    print(val_class_report)
    print("Validation Confusion Matrix:")
    print(val_conf_matrix)
    print()

    # Predict on the test data
    y_test_pred = dt_model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_class_report = classification_report(y_test, y_test_pred)
    test_conf_matrix = confusion_matrix(y_test, y_test_pred)

    print(f"Test Accuracy: {test_accuracy:.2f}")
    print("Test Classification Report:")
    print(test_class_report)
    print("Test Confusion Matrix:")
    print(test_conf_matrix)

Model: Decision Tree
Cross-validation scores: [0.89912568 0.8986484  0.89824766 0.89784692 0.89784692]
Mean cross-validation score: 0.8983431154090636

Model: Logistic Regression
Validation Accuracy: 0.90
Validation Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.67      0.74      1819
           1       0.00      0.00      0.00       928
           2       0.96      1.00      0.98      7789
           3       0.83      1.00      0.91      4714

    accuracy                           0.90     15250
   macro avg       0.65      0.67      0.66     15250
weighted avg       0.85      0.90      0.87     15250

Validation Confusion Matrix:
[[1217    0    0  602]
 [ 269    0  316  343]
 [   0    0 7789    0]
 [   3    0    0 4711]]

Test Accuracy: 0.89
Test Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.66      0.73      4741
           1       0.00      0.00      0.00   

In [ ]:
# Random forest implementation
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

# Assume X and y are your features and target variables
# X, y = your_data_features, your_data_target

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grids
param_grids = [
    {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 10, 20],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4]
    },
    {
        'n_estimators': [30, 60, 120],
        'max_depth': [None, 7, 14],
        'min_samples_split': [4, 8, 12],
        'min_samples_leaf': [2, 4, 6]
    },
    {
        'n_estimators': [25, 75, 150],
        'max_depth': [None, 12, 25],
        'min_samples_split': [2, 6, 10],
        'min_samples_leaf': [1, 3, 5]
    },
    {
        'n_estimators': [40, 80, 160],
        'max_depth': [None, 6, 18],
        'min_samples_split': [3, 5, 9],
        'min_samples_leaf': [1, 3, 4]
    }
]

# Initialize a RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)

# Function to perform grid search and return results
def perform_grid_search(param_grid, X_train, y_train):
    grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, n_jobs=-1, scoring='accuracy')
    grid_search.fit(X_train, y_train)
    results_df = pd.DataFrame(grid_search.cv_results_)
    return results_df, grid_search

# Store results for comparison
results_list = []
grid_search_objects = []
best_params_list = []

# Perform grid search for each parameter grid
for i, param_grid in enumerate(param_grids):
    results_df, grid_search = perform_grid_search(param_grid, X_train, y_train)
    results_df['param_set'] = f'param_grid_{i + 1}'
    results_list.append(results_df)
    grid_search_objects.append(grid_search)
    best_params_list.append((grid_search.best_params_, grid_search.best_score_, f'param_grid_{i + 1}'))

# Concatenate results
all_results_df = pd.concat(results_list, ignore_index=True)

# Extract best scores for each parameter grid
best_scores = all_results_df.groupby('param_set')['mean_test_score'].max().reset_index()

# Print the results
print("Comparison of Best Validation Accuracy for Each Parameter Grid:")
print(best_scores)

# Print the best parameters and their scores for each parameter grid
print("\nBest parameters and their scores for each parameter grid:")
for best_params, best_score, param_set in best_params_list:
    print(f"{param_set}: {best_params} with best validation accuracy: {best_score:.4f}")

# Identify the best parameter grid overall
best_param_set = best_scores.loc[best_scores['mean_test_score'].idxmax()]

print(f"\nBest parameter set overall: {best_param_set['param_set']}")
print(f"Best cross-validation score: {best_param_set['mean_test_score']:.4f}")

# Get the best GridSearchCV object
best_grid_search = grid_search_objects[int(best_param_set['param_set'].split('_')[-1]) - 1]

# Extract the best parameters
best_params = best_grid_search.best_params_
print(f"Best parameters found: {best_params}")

# Train the best model on the entire training set using the best parameter set
best_rf_model = best_grid_search.best_estimator_

# Predict the labels for the test set
y_pred = best_rf_model.predict(X_test)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)


Comparison of Best Validation Accuracy for Each Parameter Grid:
      param_set  mean_test_score
0  param_grid_1         0.904443
1  param_grid_2         0.905342
2  param_grid_3         0.904929
3  param_grid_4         0.904863

Best parameters and their scores for each parameter grid:
param_grid_1: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 200} with best validation accuracy: 0.9044
param_grid_2: {'max_depth': 14, 'min_samples_leaf': 2, 'min_samples_split': 8, 'n_estimators': 120} with best validation accuracy: 0.9053
param_grid_3: {'max_depth': 12, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 150} with best validation accuracy: 0.9049
param_grid_4: {'max_depth': 18, 'min_samples_leaf': 4, 'min_samples_split': 9, 'n_estimators': 160} with best validation accuracy: 0.9049

Best parameter set overall: param_grid_2
Best cross-validation score: 0.9053
Best parameters found: {'max_depth': 14, 'min_samples_leaf': 2, 'min_samples_spli

In [ ]:
#from sklearn.model_selection import cross_val_score

degree = [2, 3, 4, 5, 6, 7]

# Define models with hyperparameters
models = [
    DecisionTreeClassifier(max_depth=10, min_samples_split=5, min_samples_leaf=2),
    RandomForestClassifier(n_estimators=100, max_depth=10, min_samples_split=5, min_samples_leaf=2),
]

# Fit and evaluate each model
for model in models:
    # Compute cross-validation scores
    try:
        cv_scores = cross_val_score(model, X_train, y_train, cv=5)
        print(f"Model: {model.__class__.__name__}")
        print(f"Cross-validation scores: {cv_scores}")
        print(f"Mean cross-validation score: {np.mean(cv_scores)}\n")
    except ValueError as e:
        print(f"Error in model {model.__class__.__name__}: {e}")
        continue

    # Fit the model on the training data
    model.fit(X_train, y_train)

    # Predict on the validation data
    y_val_pred = model.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    val_class_report = classification_report(y_val, y_val_pred)
    val_conf_matrix = confusion_matrix(y_val, y_val_pred)

    print(f"Model: {model.__class__.__name__}")
    print(f"Validation Accuracy: {val_accuracy:.2f}")
    print("Validation Classification Report:")
    print(val_class_report)
    print("Validation Confusion Matrix:")
    print(val_conf_matrix)
    print()

    # Predict on the test data
    y_test_pred = model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_class_report = classification_report(y_test, y_test_pred)
    test_conf_matrix = confusion_matrix(y_test, y_test_pred)

    print(f"Test Accuracy: {test_accuracy:.2f}")
    print("Test Classification Report:")
    print(test_class_report)
    print("Test Confusion Matrix:")
    print(test_conf_matrix)
    print()

# Evaluate Logistic Regression with Polynomial Features separately
for deg in degree:
    lg_model = make_pipeline(PolynomialFeatures(deg), LogisticRegression(C=1.0, solver='saga', max_iter=200))

    try:
        cv_scores = cross_val_score(lg_model, X_train, y_train, cv=5)
        print(f"Logistic Regression with Polynomial Degree {deg}")
        print(f"Cross-validation scores: {cv_scores}")
        print(f"Mean cross-validation score: {np.mean(cv_scores)}\n")
    except ValueError as e:
        print(f"Error in Logistic Regression with Polynomial Degree {deg}: {e}")
        continue

    # Fit the model on the training data
    lg_model.fit(X_train, y_train)

    # Predict on the validation data
    y_val_pred = lg_model.predict(X_val)
    val_accuracy = accuracy_score(y_val, y_val_pred)
    val_class_report = classification_report(y_val, y_val_pred)
    val_conf_matrix = confusion_matrix(y_val, y_val_pred)

    print(f"Logistic Regression with Polynomial Degree {deg}")
    print(f"Validation Accuracy: {val_accuracy:.2f}")
    print("Validation Classification Report:")
    print(val_class_report)
    print("Validation Confusion Matrix:")
    print(val_conf_matrix)
    print()

    # Predict on the test data
    y_test_pred = lg_model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_class_report = classification_report(y_test, y_test_pred)
    test_conf_matrix = confusion_matrix(y_test, y_test_pred)

    print(f"Logistic Regression with Polynomial Degree {deg}")
    print(f"Test Accuracy: {test_accuracy:.2f}")
    print("Test Classification Report:")
    print(test_class_report)
    print("Test Confusion Matrix:")
    print(test_conf_matrix)
    #print()


Model: DecisionTreeClassifier
Cross-validation scores: [0.90229508 0.90268533 0.90445588 0.90393128 0.90209515]
Mean cross-validation score: 0.9030925453616054

Model: DecisionTreeClassifier
Validation Accuracy: 0.91
Validation Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.66      0.74      1819
           1       0.73      0.25      0.37       928
           2       0.97      1.00      0.98      7789
           3       0.85      0.99      0.92      4714

    accuracy                           0.91     15250
   macro avg       0.85      0.72      0.75     15250
weighted avg       0.90      0.91      0.90     15250

Validation Confusion Matrix:
[[1192   34    0  593]
 [ 208  229  262  229]
 [   0   16 7773    0]
 [   4   36    0 4674]]

Test Accuracy: 0.90
Test Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.64      0.72      4741
           1       0.61      0.19 